### ISSUE TITLE
Currently displayed journal page not highlighted correctly in Boundaries for Journals

### ISSUE THREAD

**Issue by ncadou** [YU000jp/logseq-plugin-show-weekday-and-week-number#40]
Here's an example, showing June 6th highlighted as June 5th. Presumably it's related to the fact that my `config.edn` file specifies this: `:start-of-week 0`

![Screen Shot 2023-06-07 at 15 01 31](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/167142/8005352f-b20c-41c2-9c92-a8ca60594fc3)

**Comment by YU000jp** [comment]
I see. It is a bug.

**Comment by YU000jp** [comment]
I anticipate that the bug is not occurring every time. It is likely due to the boundaries not being updated after the date changes in real-time. We will take measures to address this issue.

**Comment by ncadou** [comment]
In my case it is occurring every time. I don't remember every seeing to correct behavior.

**Comment by YU000jp** [comment]
Based on the information on the open date page, I believe there is some issue with the process of calculating the date. Since the bug cannot be reproduced, I have performed refactoring. Could you please verify it in the new release?

**Comment by ncadou** [comment]
I upgraded, but no change, same behavior.

**Comment by YU000jp** [comment]
I would appreciate it if you could help me with debugging. Please change the setting in Logseq to Developer Mode and open the page data from the context menu. I would like you to check if the date of 'block/journal-day' matches the current date.

![image](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/111847207/380c7370-a13f-482e-a180-dfaf6dd2e40a)

**Comment by ncadou** [comment]
Here you go: 
![Screenshot_2023-06-09_14-57-18](https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/assets/167142/1eef3e61-0f4c-4759-9cdf-26fff20c89f9)

**Comment by YU000jp** [comment]
Thank you very much. I think the issue may have been caused by including time zone information in the date.(https://github.com/YU000jp/logseq-plugin-show-weekday-and-week-number/commit/bd8a11dec4bafc135cf3912314075f945f9fc993) I have released a new update.

**Comment by ncadou** [comment]
Thanks for this. I have tried 1.14.0, but I still see the same behavior. I quit and restarted Logseq just in case, but it's the same.

**Comment by ncadou** [comment]
Actually, there is one change. Upon starting up Logseq, the correct date is highlighted, both in the case of the first page loaded being Journals or any particular journal day. Highlighting errors occur only after I click on anything to load another journal, the only exception being when I click on "Journals" on my left menu. Clicking on "Journals" is the only action I could find that results in the correct day being highlighted in the Boundaries.

**Comment by ncadou** [comment]
FYI I have upgraded to 1.15.0, same issue.

**Comment by YU000jp** [comment]
The issue should be resolved. By changing the time zone in Windows, it was possible to reproduce the symptoms. The problem was caused by the UTC time zone being applied due to parsing the date with JavaScript using `new Date()`.

**Comment by ncadou** [comment]
Yes, works fine now. Many thanks, and good catch!
